### ISSUE TITLE
Required config property "watch" missing

### ISSUE THREAD

**Issue by sherifsaleh** [wildbit/mailmason#36]
Running "watch" task
Waiting...
Verifying property watch exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch" missing.

Running "watch" task
Waiting...
Verifying property watch exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch" missing.

**Comment by armiiller** [comment]
Delete the comments in the config.json file

**Comment by gwillem** [comment]
Doesn't help here. And there is no `watch` in `https://github.com/wildbit/mailmason/blob/master/example_config.json` ?

**Comment by armiiller** [comment]
It breaks because the config file is invalid when you just copy and paste. Delete all the lines starting with '//'. There is no such syntax for comments in JSON. That's why you get the error

Verifying property watch exists in config...ERROR

Unable to process task.
Warning: Required config property "watch" missing.

because it doesn't understand the config file

**Comment by JHerz** [comment]
Mine broke because the secrets.json file that the docs say to copy is missing a comma between "s3" and "postmark".

**Comment by derekrushforth** [comment]
@sherifsaleh Are you still experiencing this issue? Removing the comments in `config.json` and `secrets.json` should fix the issue.

We just [released some updates](https://github.com/wildbit/mailmason/releases/tag/v1.0.0) today that removes these comments from `example_config.json` and `example_secrets.json` so this is less likely to happen.

@JHerz Thanks for bringing this up. I fixed the example in the wiki.

**Comment by rthickling** [comment]
FYI, I had a similar problem.
The cause was an error in my syntax.  With JSON, trailing commas are not acceptable - while they are in similar constructs in other languages, such as dictionaries in Python.
So I had:
`{
  "strings": {
    "sender_name": "Acme",
    "product_name": "RocketPack",
    "formal_company_name": "Acme Ltd",
    "product_url": "https://acme.com",
    "address_line_1": "Desert Highway, New Mexico, USA",
  }
}`

This would have been fine as a dictionary (of dictionaries) in Python, but that last comma caused endless errors and a crash with JSON in Javascript.
