### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by viperfx** [wildbit/mailmason#40]
The grunt config has `livereload` set to True, but when I open previews.html and make a change this does not reload the templates.

is there extra configuration needed?

**Comment by derekrushforth** [comment]
Thanks for the heads up @viperfx. I just pushed up a fix. `previews.html` should now reload each time you make a change to a template. You might need to wait a few seconds before the page reloads because grunt needs to finish compiling the templates though.

I also updated `livereload`'s default port to `3000`. If you want to change the port you'll need to update the [grunt task](https://github.com/wildbit/mailmason/blob/master/Gruntfile.js#L241) and the script tag in [`previews.html`](https://github.com/wildbit/mailmason/blob/master/previews.html#L7).
